language: csharp
#dotnet: 2.1.500
mono: none
dotnet: 3.0.101
sudo: false
dist: trusty
env:
  - PATH=$PATH:/home/travis/.dotnet/tools
script:
  - dotnet tool install fake-cli -g
  - dotnet tool install paket -g
  - fake run build.fsx target Build
