name: Publish to Nuget

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .
        
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.x
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
    - name: publish.ps1
      env:
          nuget_push: ${{ secrets.NUGET_API_KEY }}
      run: dotnet fsi build.fsx publish
