name: Publish Docs to GH Pages

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3

      - name: Build / Release
        shell: pwsh
        run: ./docu.ps1

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./Docu


    
